[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "fstdtools"
dynamic = ["version"]
authors = [{ name = "Moujie Qin", email = "moujieqin@gmail.com" }]
description = "CLI tools to compile/search/list/info fstd dictionary and convert mdx/mdd to fstdx/fstdd"
requires-python = ">=3.9"
license-files = ["LICENSE"]
dependencies = [
    "fstd>=0.1.6",         
    "click>=8.0", 
    "tqdm>=4.64.0"        
]

[project.scripts]
fstdtools = "fstdtools.cli:cli"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools.dynamic]
version = { file = "VERSION" }