name: Test Publish to TestPyPI

on:
    # This enables the manual "Run workflow" button in the GitHub UI
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install build tools
              run: |
                  python -m pip install --upgrade pip
                  pip install build

            - name: Build package
              run: python -m build

        # - name: Publish to TestPyPI
        #   uses: pypa/gh-action-pypi-publish@release/v1
        #   with:
        #     # This tells the action to upload to the sandbox TestPyPI site
        #     repository-url: https://test.pypi.org/legacy/
